# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: registry.gitlab.com/aknosis/laravel-ci-example:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:5.7

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - vendor/
  - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  # Install Composer and project dependencies.
  - composer install 
  - composer update

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache
  - php artisan route:cache

  # Run database migrations.
  - php artisan migrate

  # Run database seed
  - php artisan db:seed

stages:
  - production

production:
  type: deploy
  stage: production
  image: registry.gitlab.com/aknosis/laravel-ci-example:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
